include: package:very_good_analysis/analysis_options.5.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
    require_trailing_commas: false
    library_private_types_in_public_api: false
    prefer_constructors_over_static_methods: false
    one_member_abstracts: false
    no_default_cases: false
    prefer_asserts_with_message: false
