name: try_starter
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc: ^7.2.0
  dartz: ^0.10.0
  dio: ^4.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_localizations:
    sdk: flutter
  get: ^4.3.8
  get_it: ^7.2.0
  intl: ^0.17.0
  json_annotation: ^4.1.0
  rxdart: ^0.27.2
  shared_preferences: ^2.0.8

dev_dependencies:
  bloc_test: ^8.2.0
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  json_serializable: ^5.0.2
  mocktail: ^0.1.0
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/language/
    - assets/i18n/
