name: try_starter
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc: ^8.1.2
  dartz: ^0.10.0
  dio: ^5.3.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  get: ^4.3.8
  get_it: ^7.2.0
  google_fonts: ^5.1.0
  intl: ^0.18.1
  json_annotation: ^4.1.0
  rxdart: ^0.27.2
  shared_preferences: ^2.2.0

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/language/
    - assets/i18n/
